const now = new Date()
function daysFromNow(d: number) {
  return new Date(now.getTime() + d * 24 * 60 * 60 * 1000)
}
function daysAgo(d: number) {
  return new Date(now.getTime() - d * 24 * 60 * 60 * 1000)
}
function hoursAgo(h: number) {
  return new Date(now.getTime() - h * 3600000)
}

// ── Providers ─────────────────────────────────────────────
export const mockProviders = [
  {
    id: 'p1',
    name: 'CloudVPS Pro',
    type: 'VPS_PROVIDER' as const,
    website: 'https://cloudvpspro.example.com',
    contactName: 'John Smith',
    contactMethod: 'Telegram: @cloudvpspro',
    billingUrl: 'https://billing.cloudvpspro.example.com',
    notes: '主要 VPS 供应商，机房在美国和欧洲',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(2),
    _count: { vpsAssets: 2, socks5Assets: 0 },
  },
  {
    id: 'p2',
    name: 'SocksWorld',
    type: 'SOCKS5_PROVIDER' as const,
    website: 'https://socksworld.example.com',
    contactName: 'Alex',
    contactMethod: 'WhatsApp: +1234567890',
    billingUrl: null,
    notes: 'SOCKS5 代理供应商，提供住宅 IP',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
    _count: { vpsAssets: 0, socks5Assets: 3 },
  },
  {
    id: 'p3',
    name: 'NetAll Solutions',
    type: 'MIXED' as const,
    website: 'https://netall.example.com',
    contactName: 'David Chen',
    contactMethod: 'Email: david@netall.example.com',
    billingUrl: 'https://billing.netall.example.com',
    notes: '综合供应商，同时提供 VPS 和代理服务',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(1),
    _count: { vpsAssets: 1, socks5Assets: 2 },
  },
]

// ── Customers ─────────────────────────────────────────────
export const mockCustomers = [
  {
    id: 'c1',
    name: '客户 A - 电商运营',
    contact: 'Telegram: @customerA',
    platform: 'Telegram',
    status: 'ACTIVE' as const,
    notes: '主要做跨境电商',
    createdAt: daysAgo(100),
    updatedAt: daysAgo(3),
    _count: { assignments: 2 },
  },
  {
    id: 'c2',
    name: '客户 B - 数据采集',
    contact: 'WeChat: customerB',
    platform: 'WeChat',
    status: 'ACTIVE' as const,
    notes: '数据采集用途',
    createdAt: daysAgo(80),
    updatedAt: daysAgo(7),
    _count: { assignments: 1 },
  },
  {
    id: 'c3',
    name: '客户 C - 测试',
    contact: 'Email: test@example.com',
    platform: 'Email',
    status: 'INACTIVE' as const,
    notes: '测试客户，暂停使用',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(10),
    _count: { assignments: 0 },
  },
]

// ── VPS Assets ────────────────────────────────────────────
export const mockVpsAssets = [
  {
    id: 'v1',
    name: 'US-East-01',
    ip: '203.0.113.10',
    hostname: 'us-east-01.example.com',
    sshPort: 22,
    sshUsername: 'root',
    encryptedSecret: 'sk_live_abc123def456ghi789',
    providerId: 'p1',
    country: 'US',
    city: 'New York',
    asn: 'AS14618',
    asOrganization: 'Amazon.com, Inc.',
    isp: 'AWS',
    status: 'ONLINE' as const,
    purchaseDate: daysAgo(90),
    expireDate: daysFromNow(60),
    costAmount: 10.00,
    costCurrency: 'USD',
    hasThreeXui: true,
    threeXuiUrl: 'http://203.0.113.10:2053',
    assignedCustomerId: 'c1',
    tags: 'production,us-east',
    notes: '主力 VPS，运行 3x-ui 面板',
    osName: 'Ubuntu 22.04',
    cpuCores: 2,
    memoryMb: 2048,
    diskGb: 40,
    bandwidthMbps: 1000,
    trafficTotalGb: 1000,
    trafficUsedGb: 356.5,
    trafficRemainingGb: 643.5,
    trafficUpdatedAt: hoursAgo(2),
    lastStartedAt: daysAgo(12),
    lastRestartedAt: daysAgo(12),
    uptimeHours: 288,
    monitoringMode: 'SSH_SYSTEM' as const,
    allocationMode: 'SHARED' as const,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
    provider: mockProviders[0],
    assignedCustomer: mockCustomers[0],
  },
  {
    id: 'v2',
    name: 'EU-West-01',
    ip: '203.0.113.20',
    hostname: 'eu-west-01.example.com',
    sshPort: 2222,
    sshUsername: 'root',
    encryptedSecret: 'key_eu_west_secret_data_here',
    providerId: 'p1',
    country: 'DE',
    city: 'Frankfurt',
    asn: 'AS16509',
    asOrganization: 'Amazon.com, Inc.',
    isp: 'AWS EU',
    status: 'OFFLINE' as const,
    purchaseDate: daysAgo(60),
    expireDate: daysFromNow(90),
    costAmount: 15.00,
    costCurrency: 'USD',
    hasThreeXui: false,
    threeXuiUrl: null,
    assignedCustomerId: null,
    tags: 'europe,backup',
    notes: '欧洲节点，当前离线待排查',
    osName: 'Debian 12',
    cpuCores: 1,
    memoryMb: 1024,
    diskGb: 25,
    bandwidthMbps: 500,
    trafficTotalGb: 500,
    trafficUsedGb: 120.3,
    trafficRemainingGb: 379.7,
    trafficUpdatedAt: hoursAgo(5),
    lastStartedAt: daysAgo(20),
    lastRestartedAt: null,
    uptimeHours: null,
    monitoringMode: 'DISABLED' as const,
    allocationMode: 'SHARED' as const,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
    provider: mockProviders[0],
    assignedCustomer: null,
  },
  {
    id: 'v3',
    name: 'APAC-01 即将到期',
    ip: '203.0.113.30',
    hostname: null,
    sshPort: 22,
    sshUsername: 'root',
    encryptedSecret: 'apac_secret_token_xyz',
    providerId: 'p3',
    country: 'SG',
    city: 'Singapore',
    asn: 'AS16509',
    asOrganization: 'Amazon.com, Inc.',
    isp: 'AWS APAC',
    status: 'ONLINE' as const,
    purchaseDate: daysAgo(30),
    expireDate: daysFromNow(5),
    costAmount: 8.00,
    costCurrency: 'USD',
    hasThreeXui: true,
    threeXuiUrl: 'http://203.0.113.30:2053',
    assignedCustomerId: null,
    tags: 'apac,expiring',
    notes: '5 天后到期，需要续费',
    osName: 'Ubuntu 20.04',
    cpuCores: 4,
    memoryMb: 4096,
    diskGb: 80,
    bandwidthMbps: 2000,
    trafficTotalGb: 2000,
    trafficUsedGb: 1850.2,
    trafficRemainingGb: 149.8,
    trafficUpdatedAt: hoursAgo(1),
    lastStartedAt: daysAgo(6),
    lastRestartedAt: daysAgo(6),
    uptimeHours: 144,
    monitoringMode: 'THREE_X_UI' as const,
    allocationMode: 'SHARED' as const,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
    provider: mockProviders[2],
    assignedCustomer: null,
  },
]

// ── SOCKS5 Assets ─────────────────────────────────────────
export const mockSocks5Assets = [
  {
    id: 's1',
    name: 'US-Residential-01',
    host: 'proxy1.example.com',
    port: 1080,
    username: 'user1',
    encryptedSecret: 'socks5_pass_user1_secret',
    providerId: 'p2',
    country: 'US',
    city: 'Los Angeles',
    asn: 'AS7922',
    asOrganization: 'Comcast Cable',
    isp: 'Comcast',
    status: 'ONLINE' as const,
    purchaseDate: daysAgo(60),
    expireDate: daysFromNow(45),
    costAmount: 5.00,
    costCurrency: 'USD',
    supportsUdp: true,
    relayVpsId: null,
    assignedCustomerId: 'c1',
    tags: 'residential,us',
    notes: '住宅 IP，支持 UDP',
    trafficTotalGb: 200,
    trafficUsedGb: 85.3,
    trafficRemainingGb: 114.7,
    trafficUpdatedAt: hoursAgo(3),
    outboundIp: '198.51.100.10',
    authType: 'username_password',
    usesRelayVps: false,
    relayMode: 'DIRECT' as const,
    trafficSyncMode: null,
    allocationMode: 'EXCLUSIVE' as const,
    lastStartedAt: daysAgo(25),
    uptimeHours: 600,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(3),
    provider: mockProviders[1],
    assignedCustomer: mockCustomers[0],
    relayVps: null,
  },
  {
    id: 's2',
    name: 'UK-Datacenter-01',
    host: 'proxy2.example.com',
    port: 1080,
    username: 'user2',
    encryptedSecret: 'socks5_pass_user2_secret',
    providerId: 'p2',
    country: 'GB',
    city: 'London',
    asn: 'AS13335',
    asOrganization: 'Cloudflare, Inc.',
    isp: 'Cloudflare',
    status: 'ONLINE' as const,
    purchaseDate: daysAgo(45),
    expireDate: daysFromNow(120),
    costAmount: 3.00,
    costCurrency: 'USD',
    supportsUdp: false,
    relayVpsId: null,
    assignedCustomerId: 'c2',
    tags: 'datacenter,uk',
    notes: null,
    trafficTotalGb: 500,
    trafficUsedGb: 230.1,
    trafficRemainingGb: 269.9,
    trafficUpdatedAt: hoursAgo(6),
    outboundIp: '198.51.100.20',
    authType: 'username_password',
    usesRelayVps: false,
    relayMode: 'DIRECT' as const,
    trafficSyncMode: null,
    allocationMode: 'EXCLUSIVE' as const,
    lastStartedAt: daysAgo(30),
    uptimeHours: 720,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
    provider: mockProviders[1],
    assignedCustomer: mockCustomers[1],
    relayVps: null,
  },
  {
    id: 's3',
    name: 'JP-Residential-01',
    host: 'proxy3.example.com',
    port: 1080,
    username: 'user3',
    encryptedSecret: 'socks5_pass_user3_secret',
    providerId: 'p3',
    country: 'JP',
    city: 'Tokyo',
    asn: 'AS2516',
    asOrganization: 'KDDI CORPORATION',
    isp: 'KDDI',
    status: 'OFFLINE' as const,
    purchaseDate: daysAgo(30),
    expireDate: daysFromNow(80),
    costAmount: 7.00,
    costCurrency: 'USD',
    supportsUdp: false,
    relayVpsId: null,
    assignedCustomerId: null,
    tags: 'japan,residential',
    notes: '日本住宅 IP，当前离线',
    trafficTotalGb: 300,
    trafficUsedGb: 45.0,
    trafficRemainingGb: 255.0,
    trafficUpdatedAt: hoursAgo(8),
    outboundIp: '198.51.100.30',
    authType: 'username_password',
    usesRelayVps: false,
    relayMode: 'DIRECT' as const,
    trafficSyncMode: null,
    allocationMode: 'EXCLUSIVE' as const,
    lastStartedAt: daysAgo(8),
    uptimeHours: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
    provider: mockProviders[2],
    assignedCustomer: null,
    relayVps: null,
  },
  {
    id: 's4',
    name: 'DE-ISP-01',
    host: 'proxy4.example.com',
    port: 1080,
    username: 'user4',
    encryptedSecret: 'socks5_pass_user4_secret',
    providerId: 'p3',
    country: 'DE',
    city: 'Berlin',
    asn: 'AS3320',
    asOrganization: 'Deutsche Telekom AG',
    isp: 'Deutsche Telekom',
    status: 'IDLE' as const,
    purchaseDate: daysAgo(20),
    expireDate: daysFromNow(200),
    costAmount: 4.50,
    costCurrency: 'EUR',
    supportsUdp: true,
    relayVpsId: 'v2',
    assignedCustomerId: null,
    tags: 'germany,idle',
    notes: '空闲状态，可分配给客户',
    trafficTotalGb: 100,
    trafficUsedGb: 12.8,
    trafficRemainingGb: 87.2,
    trafficUpdatedAt: hoursAgo(10),
    outboundIp: '198.51.100.40',
    authType: 'username_password',
    usesRelayVps: true,
    relayMode: 'VPS_RELAY' as const,
    relayServiceType: 'GOST' as const,
    relayListenHost: '0.0.0.0',
    relayListenPort: 1080,
    relayProtocol: 'tcp',
    relayTag: 'de-relay-01',
    trafficSyncMode: 'RELAY_NODE' as const,
    allocationMode: 'EXCLUSIVE' as const,
    lastStartedAt: daysAgo(5),
    uptimeHours: 120,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
    provider: mockProviders[2],
    assignedCustomer: null,
    relayVps: mockVpsAssets[1],
  },
  {
    id: 's5',
    name: 'FR-Residential 即将到期',
    host: 'proxy5.example.com',
    port: 1080,
    username: 'user5',
    encryptedSecret: 'socks5_pass_user5_secret',
    providerId: 'p2',
    country: 'FR',
    city: 'Paris',
    asn: 'AS3215',
    asOrganization: 'Orange S.A.',
    isp: 'Orange',
    status: 'ONLINE' as const,
    purchaseDate: daysAgo(15),
    expireDate: daysFromNow(3),
    costAmount: 6.00,
    costCurrency: 'EUR',
    supportsUdp: false,
    relayVpsId: null,
    assignedCustomerId: null,
    tags: 'france,expiring',
    notes: '3 天后到期',
    trafficTotalGb: 150,
    trafficUsedGb: 142.5,
    trafficRemainingGb: 7.5,
    trafficUpdatedAt: hoursAgo(4),
    outboundIp: '198.51.100.50',
    authType: 'username_password',
    usesRelayVps: false,
    relayMode: 'DIRECT' as const,
    trafficSyncMode: null,
    allocationMode: 'EXCLUSIVE' as const,
    lastStartedAt: daysAgo(7),
    uptimeHours: 168,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
    provider: mockProviders[1],
    assignedCustomer: null,
    relayVps: null,
  },
]

// ── Install Tasks ─────────────────────────────────────────
export const mockInstallTasks = [
  {
    id: 'it1',
    vpsAssetId: 'v1',
    installType: 'THREE_X_UI',
    installUrl: 'https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh',
    installCommand: null,
    status: 'SUCCESS',
    outputLog: `正在下载 3x-ui 安装脚本...\n检测到系统: Ubuntu 22.04\n安装依赖包...\n正在安装 3x-ui v2.3.6...\n安装完成!\n\n============================================\n  3X-UI 安装成功\n  面板地址: http://203.0.113.10:2053\n  用户名: admin\n  初始密码: admin\n  端口: 2053\n  请尽快修改默认密码!\n============================================\n\nStarting 3x-ui service...\n3x-ui 服务已启动`,
    parsedResult: {
      panelUrl: 'http://203.0.113.10:2053',
      port: 2053,
      username: 'admin',
      password: 'admin',
      version: 'v2.3.6',
      serviceStatus: 'running',
    },
    startedAt: daysAgo(80),
    finishedAt: daysAgo(80),
    createdAt: daysAgo(80),
    updatedAt: daysAgo(80),
  },
  {
    id: 'it2',
    vpsAssetId: 'v3',
    installType: 'THREE_X_UI',
    installUrl: 'https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh',
    installCommand: null,
    status: 'SUCCESS',
    outputLog: `检测到系统: Ubuntu 20.04\n安装 3x-ui v2.3.6...\n安装完成!\n\n面板地址: http://203.0.113.30:2053\n用户名: admin\n初始密码: demo_password_placeholder\n端口: 2053\n服务已启动`,
    parsedResult: {
      panelUrl: 'http://203.0.113.30:2053',
      port: 2053,
      username: 'admin',
      password: 'demo_password_placeholder',
      version: 'v2.3.6',
      serviceStatus: 'running',
    },
    startedAt: daysAgo(25),
    finishedAt: daysAgo(25),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: 'it3',
    vpsAssetId: 'v2',
    installType: 'THREE_X_UI',
    installUrl: 'https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh',
    installCommand: null,
    status: 'FAILED',
    outputLog: `正在连接 VPS...\nSSH 连接超时: Connection refused\n安装失败: 无法连接到目标服务器`,
    parsedResult: null,
    startedAt: daysAgo(10),
    finishedAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
]

// ── Assignments ───────────────────────────────────────────
export const mockAssignments = [
  {
    id: 'a1',
    customerId: 'c1',
    assetType: 'VPS' as const,
    vpsAssetId: 'v1',
    socks5AssetId: null,
    usageStartDate: daysAgo(85),
    customerExpireDate: daysFromNow(30), // 客户到期 < 资源到期(60天)
    actualEndDate: null,
    status: 'ACTIVE' as const,
    notes: '客户 A 使用 US-East VPS',
    // 交付信息
    deliveryMethod: 'SSH',
    deliveryHost: '203.0.113.10',
    deliveryPort: 22,
    deliveryUsername: 'root',
    deliveryPasswordMasked: '******',
    deliveryLink: null,
    servicePlanName: '高级版',
    customerPriceAmount: 25.00,
    customerPriceCurrency: 'USD',
    createdAt: daysAgo(85),
    updatedAt: daysAgo(5),
    customer: mockCustomers[0],
    vpsAsset: mockVpsAssets[0],
    socks5Asset: null,
  },
  {
    id: 'a2',
    customerId: 'c1',
    assetType: 'SOCKS5' as const,
    vpsAssetId: null,
    socks5AssetId: 's1',
    usageStartDate: daysAgo(55),
    customerExpireDate: daysFromNow(45),
    actualEndDate: null,
    status: 'ACTIVE' as const,
    notes: '客户 A 使用 US 住宅代理',
    deliveryMethod: 'SOCKS5',
    deliveryHost: 'proxy1.example.com',
    deliveryPort: 1080,
    deliveryUsername: 'user1',
    deliveryPasswordMasked: '******',
    deliveryLink: null,
    servicePlanName: '基础版',
    customerPriceAmount: 10.00,
    customerPriceCurrency: 'USD',
    createdAt: daysAgo(55),
    updatedAt: daysAgo(3),
    customer: mockCustomers[0],
    vpsAsset: null,
    socks5Asset: mockSocks5Assets[0],
  },
  {
    id: 'a3',
    customerId: 'c2',
    assetType: 'SOCKS5' as const,
    vpsAssetId: null,
    socks5AssetId: 's2',
    usageStartDate: daysAgo(40),
    customerExpireDate: daysFromNow(140), // 客户到期(140) > 资源到期(120) — 风险!
    actualEndDate: null,
    status: 'ACTIVE' as const,
    notes: '客户 B 使用 UK 机房代理 — ⚠ 客户到期超过资源到期',
    deliveryMethod: 'SOCKS5',
    deliveryHost: 'proxy2.example.com',
    deliveryPort: 1080,
    deliveryUsername: 'user2',
    deliveryPasswordMasked: '******',
    deliveryLink: null,
    servicePlanName: '标准版',
    customerPriceAmount: 8.00,
    customerPriceCurrency: 'USD',
    createdAt: daysAgo(40),
    updatedAt: daysAgo(10),
    customer: mockCustomers[1],
    vpsAsset: null,
    socks5Asset: mockSocks5Assets[1],
  },
  // 历史记录 — 已结束
  {
    id: 'a4',
    customerId: 'c2',
    assetType: 'VPS' as const,
    vpsAssetId: 'v2',
    socks5AssetId: null,
    usageStartDate: daysAgo(50),
    customerExpireDate: daysAgo(10),
    actualEndDate: daysAgo(10),
    status: 'ENDED' as const,
    notes: '客户 B 之前使用 EU-West VPS，已结束',
    deliveryMethod: null,
    deliveryHost: null,
    deliveryPort: null,
    deliveryUsername: null,
    deliveryPasswordMasked: null,
    deliveryLink: null,
    servicePlanName: null,
    customerPriceAmount: null,
    customerPriceCurrency: 'USD',
    createdAt: daysAgo(50),
    updatedAt: daysAgo(10),
    customer: mockCustomers[1],
    vpsAsset: mockVpsAssets[1],
    socks5Asset: null,
  },
]

// ── Health Check Logs ─────────────────────────────────────
export const mockHealthCheckLogs = [
  { id: 'h1', assetType: 'VPS' as const, vpsAssetId: 'v1', socks5AssetId: null, checkType: 'TCP' as const, status: 'SUCCESS' as const, latencyMs: 120, message: 'OK', checkedAt: hoursAgo(1) },
  { id: 'h2', assetType: 'VPS' as const, vpsAssetId: 'v1', socks5AssetId: null, checkType: 'SSH' as const, status: 'SUCCESS' as const, latencyMs: 85, message: 'OK', checkedAt: hoursAgo(2) },
  { id: 'h3', assetType: 'VPS' as const, vpsAssetId: 'v2', socks5AssetId: null, checkType: 'TCP' as const, status: 'FAILED' as const, latencyMs: null, message: 'Connection refused', checkedAt: hoursAgo(3) },
  { id: 'h4', assetType: 'VPS' as const, vpsAssetId: 'v3', socks5AssetId: null, checkType: 'THREE_X_UI' as const, status: 'SUCCESS' as const, latencyMs: 200, message: 'OK', checkedAt: hoursAgo(4) },
  { id: 'h5', assetType: 'VPS' as const, vpsAssetId: 'v1', socks5AssetId: null, checkType: 'PING' as const, status: 'SUCCESS' as const, latencyMs: 45, message: 'OK', checkedAt: hoursAgo(5) },
  { id: 'h6', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's1', checkType: 'SOCKS5_AUTH' as const, status: 'SUCCESS' as const, latencyMs: 30, message: 'OK', checkedAt: hoursAgo(6) },
  { id: 'h7', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's2', checkType: 'HTTP_OUTBOUND' as const, status: 'FAILED' as const, latencyMs: null, message: 'Auth failed', checkedAt: hoursAgo(7) },
  { id: 'h8', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's3', checkType: 'DNS' as const, status: 'SUCCESS' as const, latencyMs: 150, message: 'OK', checkedAt: hoursAgo(8) },
  { id: 'h9', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's4', checkType: 'UDP' as const, status: 'SUCCESS' as const, latencyMs: 90, message: 'OK', checkedAt: hoursAgo(9) },
  { id: 'h10', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's5', checkType: 'PING' as const, status: 'TIMEOUT' as const, latencyMs: null, message: 'Request timed out', checkedAt: hoursAgo(10) },
]

// ── IP Intelligence ───────────────────────────────────────
export const mockIpIntelligence = [
  { id: 'ip1', ip: '203.0.113.10', country: 'US', city: 'New York', asn: 'AS14618', asOrganization: 'Amazon.com, Inc.', isp: 'AWS', networkType: 'DATACENTER' as const, isDatacenter: true, isResidentialLike: false, isMobileLike: false, isProxyLike: false, isVpnLike: false, internalRiskScore: 25, riskLevel: 'LOW' as const, lastCheckedAt: hoursAgo(1), notes: null, createdAt: daysAgo(90), updatedAt: hoursAgo(1) },
  { id: 'ip2', ip: '203.0.113.20', country: 'DE', city: 'Frankfurt', asn: 'AS16509', asOrganization: 'Amazon.com, Inc.', isp: 'AWS EU', networkType: 'DATACENTER' as const, isDatacenter: true, isResidentialLike: false, isMobileLike: false, isProxyLike: false, isVpnLike: false, internalRiskScore: 30, riskLevel: 'LOW' as const, lastCheckedAt: hoursAgo(2), notes: null, createdAt: daysAgo(60), updatedAt: hoursAgo(2) },
  { id: 'ip3', ip: '203.0.113.30', country: 'SG', city: 'Singapore', asn: 'AS16509', asOrganization: 'Amazon.com, Inc.', isp: 'AWS APAC', networkType: 'DATACENTER' as const, isDatacenter: true, isResidentialLike: false, isMobileLike: false, isProxyLike: false, isVpnLike: false, internalRiskScore: 20, riskLevel: 'LOW' as const, lastCheckedAt: hoursAgo(3), notes: null, createdAt: daysAgo(30), updatedAt: hoursAgo(3) },
  { id: 'ip4', ip: '198.51.100.10', country: 'US', city: 'Los Angeles', asn: 'AS7922', asOrganization: 'Comcast Cable', isp: 'Comcast', networkType: 'RESIDENTIAL' as const, isDatacenter: false, isResidentialLike: true, isMobileLike: false, isProxyLike: false, isVpnLike: false, internalRiskScore: 10, riskLevel: 'LOW' as const, lastCheckedAt: hoursAgo(4), notes: null, createdAt: daysAgo(60), updatedAt: hoursAgo(4) },
  { id: 'ip5', ip: '198.51.100.20', country: 'GB', city: 'London', asn: 'AS13335', asOrganization: 'Cloudflare, Inc.', isp: 'Cloudflare', networkType: 'DATACENTER' as const, isDatacenter: true, isResidentialLike: false, isMobileLike: false, isProxyLike: true, isVpnLike: false, internalRiskScore: 55, riskLevel: 'MEDIUM' as const, lastCheckedAt: hoursAgo(5), notes: 'Cloudflare CDN', createdAt: daysAgo(45), updatedAt: hoursAgo(5) },
  { id: 'ip6', ip: '198.51.100.30', country: 'JP', city: 'Tokyo', asn: 'AS2516', asOrganization: 'KDDI CORPORATION', isp: 'KDDI', networkType: 'ISP' as const, isDatacenter: false, isResidentialLike: true, isMobileLike: false, isProxyLike: false, isVpnLike: false, internalRiskScore: 15, riskLevel: 'LOW' as const, lastCheckedAt: hoursAgo(6), notes: null, createdAt: daysAgo(30), updatedAt: hoursAgo(6) },
  { id: 'ip7', ip: '198.51.100.40', country: 'DE', city: 'Berlin', asn: 'AS3320', asOrganization: 'Deutsche Telekom AG', isp: 'Deutsche Telekom', networkType: 'ISP' as const, isDatacenter: false, isResidentialLike: true, isMobileLike: false, isProxyLike: false, isVpnLike: false, internalRiskScore: 20, riskLevel: 'LOW' as const, lastCheckedAt: hoursAgo(7), notes: null, createdAt: daysAgo(20), updatedAt: hoursAgo(7) },
  { id: 'ip8', ip: '198.51.100.50', country: 'FR', city: 'Paris', asn: 'AS16276', asOrganization: 'OVH SAS', isp: 'OVH', networkType: 'DATACENTER' as const, isDatacenter: true, isResidentialLike: false, isMobileLike: false, isProxyLike: true, isVpnLike: true, internalRiskScore: 75, riskLevel: 'HIGH' as const, lastCheckedAt: hoursAgo(8), notes: '高风险 IP，代理 + VPN', createdAt: daysAgo(15), updatedAt: hoursAgo(8) },
]

// ── Reminders ─────────────────────────────────────────────
export const mockReminders = [
  { id: 'r1', title: 'APAC-01 VPS 即将到期', assetType: 'VPS' as const, vpsAssetId: 'v3', socks5AssetId: null, reminderType: 'VPS_EXPIRATION' as const, dueAt: daysFromNow(5), status: 'PENDING' as const, message: 'APAC-01 将在 5 天后到期，请及时续费', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'r2', title: 'FR-Residential SOCKS5 即将到期', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's5', reminderType: 'SOCKS5_EXPIRATION' as const, dueAt: daysFromNow(3), status: 'PENDING' as const, message: '法国住宅代理将在 3 天后到期', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
  { id: 'r3', title: 'EU-West-01 健康检查失败', assetType: 'VPS' as const, vpsAssetId: 'v2', socks5AssetId: null, reminderType: 'HEALTH_FAILURE' as const, dueAt: hoursAgo(2), status: 'PENDING' as const, message: 'EU-West-01 健康检查失败，需要排查', createdAt: hoursAgo(3), updatedAt: hoursAgo(3) },
  { id: 'r4', title: 'JP-Residential-01 离线', assetType: 'SOCKS5' as const, vpsAssetId: null, socks5AssetId: 's3', reminderType: 'HEALTH_FAILURE' as const, dueAt: hoursAgo(5), status: 'PENDING' as const, message: '日本代理已离线，需要检查', createdAt: hoursAgo(6), updatedAt: hoursAgo(6) },
  { id: 'r5', title: '手动提醒：检查客户 B 的使用情况', assetType: null, vpsAssetId: null, socks5AssetId: null, reminderType: 'MANUAL' as const, dueAt: daysFromNow(7), status: 'PENDING' as const, message: '下周需要检查客户 B 的数据采集使用情况', createdAt: daysAgo(1), updatedAt: daysAgo(1) },
]

// ── Dashboard stats (pre-computed) ────────────────────────
export const mockDashboardStats = {
  totalVps: 3,
  onlineVps: 2,
  offlineVps: 1,
  totalSocks5: 5,
  onlineSocks5: 3,
  offlineSocks5: 1,
  expiringIn7: 2,
  expiringIn30: 2,
  assignedAssets: 3,
  idleAssets: 2,
  highRiskIps: 1,
  customerExpiringIn7: 0,
  customerExpiringIn30: 1,
  customerExceedResource: 1,
}

// ── App Settings ──────────────────────────────────────────
export const mockAppSettings = [
  { id: 'as1', key: 'app_name', value: 'ProxyOps Manager', createdAt: daysAgo(120), updatedAt: daysAgo(120) },
  { id: 'as2', key: 'default_currency', value: 'USD', createdAt: daysAgo(120), updatedAt: daysAgo(120) },
]
